// <auto-generated by Rune.Generator />

use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const INVOCATION_STREAM: &str = "rune:invocations";
pub const RESULT_STREAM: &str = "rune:results";
pub const RUNNER_CONSUMER_GROUP: &str = "rune-runners";
pub const MAX_ARTIFACT_BYTES: u64 = 16777216;
pub const MAX_INVOCATION_BYTES: usize = 131072;
pub const MAX_RESULT_BYTES: usize = 262144;

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[allow(clippy::enum_variant_names)]
#[serde(rename_all = "camelCase")]
pub enum RuneApiEventType {
    MessageCreate,
    MessageDelete,
    MessageReactionAdd,
    MessageReactionRemove,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BuiltRuneArtifact {
    pub id: String,
    pub digest: String,
    pub entrypoint: String,
    pub size_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuneInvocationEnvelope {
    pub execution_id: String,
    pub invocation_id: String,
    pub rune_id: String,
    pub rune_name: String,
    pub guild_id: u64,
    pub event_type: RuneApiEventType,
    pub artifact: BuiltRuneArtifact,
    pub payload: Value,
    pub enqueued_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuneHostAction {
    pub method: String,
    pub arguments: Value,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RuneResultEnvelope {
    pub execution_id: String,
    pub invocation_id: String,
    pub rune_id: String,
    pub actions: Vec<RuneHostAction>,
    pub error: Option<String>,
}
