#!/usr/bin/env bash
set -euo pipefail

micropython_version="${MICROPYTHON_VERSION:?MICROPYTHON_VERSION is required}"

micropython=/opt/micropython
rune=/opt/rune
embed="$rune/micropython-embed"
package="$embed/micropython_embed"

git clone --depth 1 --branch "$micropython_version" \
    https://github.com/micropython/micropython.git \
    "$micropython"

# Build the Python -> .mpy compiler once for this image.
make -C "$micropython/mpy-cross" -j2
cp "$micropython/mpy-cross/build/mpy-cross" /usr/local/bin/mpy-cross

# Start with MicroPython's official embedding example.
mkdir -p "$embed"
cp -a "$micropython/examples/embedding/." "$embed/"

# Rune uses CORE as its base and adds its deliberately selected Python surface.
sed -i \
    's/MICROPY_CONFIG_ROM_LEVEL_MINIMUM/MICROPY_CONFIG_ROM_LEVEL_CORE_FEATURES/' \
    "$embed/mpconfigport.h"

cat "$rune/python/mpconfigrune.h" >> "$embed/mpconfigport.h"

mkdir -p "$embed/port"

cp "$rune/python/rune_time.h" \
    "$embed/port/rune_time.h"

# These extmods need their QSTRs generated as part of the embed package.
sed -i \
    '/include $(MICROPYTHON_TOP)\/ports\/embed\/embed.mk/i \
SRC_QSTR += $(MICROPYTHON_TOP)/extmod/modjson.c\n\
SRC_QSTR += $(MICROPYTHON_TOP)/extmod/modre.c\n\
SRC_QSTR += $(MICROPYTHON_TOP)/extmod/modrandom.c\n\
SRC_QSTR += $(MICROPYTHON_TOP)/extmod/modtime.c' \
    "$embed/micropython_embed.mk"

# Generate MicroPython's embedding package.
make -C "$embed" \
    -f micropython_embed.mk \
    MICROPYTHON_TOP="$micropython"

# Add Rune's selected extmods.
cp \
    "$micropython/extmod/modjson.c" \
    "$micropython/extmod/modre.c" \
    "$micropython/extmod/modrandom.c" \
    "$micropython/extmod/modtime.c" \
    "$micropython/extmod/modtime.h" \
    "$package/extmod/"

# Dependencies used by the selected extmods.
mkdir -p \
    "$package/lib/re1.5" \
    "$package/shared/timeutils"

find "$micropython/lib/re1.5" \
    -maxdepth 1 -type f \( -name '*.c' -o -name '*.h' \) \
    -exec cp {} "$package/lib/re1.5/" \;

find "$micropython/shared/timeutils" \
    -maxdepth 1 -type f \( -name '*.c' -o -name '*.h' \) \
    -exec cp {} "$package/shared/timeutils/" \;

# Rune-specific platform implementation.
cp "$rune/python/rune_port.c" "$package/port/rune_port.c"
cp "$rune/python/rune_time.h" "$package/port/rune_time.h"

# The stock embedding Makefile only knows about the directories generated by
# the minimal embed port. Add the Rune-selected dependencies explicitly.
sed -i \
    's|SRC += $(wildcard $(EMBED_DIR)/\*/\*.c) $(wildcard $(EMBED_DIR)/\*/\*/\*.c)|SRC += $(wildcard $(EMBED_DIR)/py/*.c) $(wildcard $(EMBED_DIR)/extmod/*.c) $(wildcard $(EMBED_DIR)/shared/runtime/*.c) $(wildcard $(EMBED_DIR)/shared/timeutils/*.c) $(wildcard $(EMBED_DIR)/port/*.c)|' \
    "$embed/Makefile"

# Floating-point math used by the configured MicroPython runtime.
sed -i \
    's/$(CC) -o $@ $^/$(CC) -o $@ $^ -lm/' \
    "$embed/Makefile"

make -C "$embed"

# Runes link against the prepared MicroPython runtime rather than rebuilding
# MicroPython for every user script.
find "$package" -name '*.o' -print0 \
    | xargs -0 ar rcs "$rune/libmicropython_embed.a"
