using System.Text;
using System.Text.Json;

namespace Rune.Api.Generator;

public static class RuneApiEmitter
{
    private const string Header = "// <auto-generated by Rune.Api.Generator />\n";

    public static IReadOnlyDictionary<string, string> Emit(RuneApiModel model)
    {
        var output = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["docs/api/generated/index.md"] = EmitDocumentation(model, null),
            ["docs/api/generated/javascript.md"] = EmitDocumentation(model, "JavaScript"),
            ["docs/api/generated/python.md"] = EmitDocumentation(model, "Python"),
            ["docs/api/generated/rust.md"] = EmitDocumentation(model, "Rust"),
            ["generated/api/model.json"] = EmitJson(model),
            ["generated/javascript/rune-api.d.ts"] = EmitTypeScript(model),
            ["generated/javascript/rune-api.js"] = EmitJavaScript(model),
            ["generated/python/rune_api.py"] = EmitPython(model),
            ["generated/python/rune_api.pyi"] = EmitPythonStubs(model),
            ["generated/rust/rune_api.rs"] = EmitRust(model),
            ["src/Rune.Bot/Api/Generated/NetCordRuneApi.g.cs"] = EmitNetCordProjection(model),
            ["src/Rune.Core/Api/Generated/RuneApi.g.cs"] = EmitManagedModel(model),
            ["wit/rune-api.wit"] = EmitWit(model)
        };

        return output;
    }

    private static string EmitWit(RuneApiModel model)
    {
        var text = new StringBuilder();
        text.Append("// <auto-generated by Rune.Api.Generator />\n");
        text.Append($"package {model.Package}@{model.Version};\n\n");
        text.Append("interface types {\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"    enum {Names.Kebab(type.Name)} {{\n");
                foreach (var member in type.Members)
                    text.Append($"        {Names.Kebab(member.Name)},\n");
                text.Append("    }\n\n");
                continue;
            }

            text.Append($"    record {Names.Kebab(type.Name)} {{\n");
            foreach (var member in type.Members)
            {
                var memberName = Names.Kebab(member.Name);
                if (memberName == "type")
                    memberName = "%type";
                text.Append($"        {memberName}: {WitType(member.Type)},\n");
            }
            text.Append("    }\n\n");
        }

        text.Append("}\n\n");

        foreach (var gatewayEvent in model.Events)
        {
            var payload = model.Types.Single(value => value.Name == gatewayEvent.Payload);
            var payloadName = Names.Kebab(payload.Name);
            var parameter = payload.Name == "Message" ? "message" : "args";
            text.Append($"world {gatewayEvent.World} {{\n");
            text.Append($"    use types.{{{payloadName}}};\n");
            text.Append("    import reply: func(content: string);\n");
            text.Append($"    export handle: func({parameter}: {payloadName});\n");
            text.Append("}\n");
            if (gatewayEvent != model.Events[^1])
                text.Append('\n');
        }

        return text.ToString();
    }

    private static string EmitManagedModel(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\n#nullable enable\n\nnamespace Rune.Core.Api.Generated;\n\n");
        text.Append($"public static class RuneApiMetadata\n{{\n    public const string Fingerprint = \"{model.Fingerprint}\";\n}}\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"public enum {type.Name}\n{{\n");
                foreach (var member in type.Members)
                    text.Append($"    {member.Name} = {member.EnumValue},\n");
                text.Append("}\n\n");
                continue;
            }

            text.Append($"public sealed record {type.Name}(\n");
            for (var index = 0; index < type.Members.Count; index++)
            {
                var member = type.Members[index];
                var suffix = index == type.Members.Count - 1 ? ");" : ",";
                text.Append($"    {CSharpType(member.Type)} {member.Name}{suffix}\n");
            }
            if (type.Members.Count == 0)
                text.Append(");\n");
            text.Append('\n');
        }

        text.Append("public enum RuneApiEvent\n{\n");
        for (var index = 0; index < model.Events.Count; index++)
            text.Append($"    {model.Events[index].Name} = {index},\n");
        text.Append("}\n");
        return text.ToString();
    }

    private static string EmitNetCordProjection(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\n#nullable enable\n\nusing RuneApi = Rune.Core.Api.Generated;\n\n");
        text.Append("namespace Rune.Bot.Api.Generated;\n\n");
        text.Append("public static class NetCordRuneApi\n{\n");

        foreach (var type in model.Types.Where(value => !value.IsEnum))
        {
            text.Append($"    public static RuneApi.{type.Name} Project(\n");
            text.Append($"        {type.NetCordName} value) =>\n");
            text.Append($"        new(\n");
            for (var index = 0; index < type.Members.Count; index++)
            {
                var member = type.Members[index];
                var suffix = index == type.Members.Count - 1 ? ");" : ",";
                text.Append($"            {ProjectionExpression(member, $"value.{member.Name}")}{suffix}\n");
            }
            if (type.Members.Count == 0)
                text.Append("        );\n");
            text.Append('\n');
        }

        text.Append("}\n");
        return text.ToString();
    }

    private static string ProjectionExpression(RuneApiMember member, string source)
    {
        if (!member.Type.IsSelectedType)
            return source;

        if (member.Type.Name == "ReactionType")
            return $"(RuneApi.ReactionType)(int){source}";

        return member.Type.Optional
            ? $"{source} is {{ }} selected ? Project(selected) : null"
            : $"Project({source})";
    }

    private static string EmitJavaScript(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append('\n');

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"export const {type.Name} = Object.freeze({{\n");
                foreach (var member in type.Members)
                    text.Append($"    {Names.Camel(member.Name)}: {member.EnumValue},\n");
                text.Append("});\n\n");
                continue;
            }

            text.Append($"export class {type.Name} {{\n");
            text.Append("    constructor(value) {\n");
            foreach (var member in type.Members)
            {
                var projected = Names.Camel(member.Name);
                var expression = member.Type.IsSelectedType && member.Type.Name != "ReactionType"
                    ? $"value.{projected} == null ? null : new {member.Type.Name}(value.{projected})"
                    : $"value.{projected}";
                text.Append($"        this.{projected} = {expression};\n");
            }
            text.Append("        Object.freeze(this);\n");
            text.Append("    }\n");
            text.Append("}\n\n");
        }

        text.Append("export const events = Object.freeze({\n");
        foreach (var gatewayEvent in model.Events)
            text.Append($"    {Names.Camel(gatewayEvent.Name)}: \"{gatewayEvent.World}\",\n");
        text.Append("});\n");
        return text.ToString();
    }

    private static string EmitTypeScript(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append('\n');
        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"export declare const {type.Name}: {{\n");
                foreach (var member in type.Members)
                    text.Append($"    readonly {Names.Camel(member.Name)}: {member.EnumValue};\n");
                text.Append("};\n\n");
                continue;
            }

            text.Append($"export declare class {type.Name} {{\n");
            foreach (var member in type.Members)
                text.Append($"    readonly {Names.Camel(member.Name)}: {TypeScriptType(member.Type)};\n");
            text.Append("    constructor(value: unknown);\n}\n\n");
        }
        return text.ToString();
    }

    private static string EmitPython(RuneApiModel model)
    {
        var text = new StringBuilder("# <auto-generated by Rune.Api.Generator />\n\n");
        text.Append("from dataclasses import dataclass\nfrom enum import IntEnum\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"class {type.Name}(IntEnum):\n");
                foreach (var member in type.Members)
                    text.Append($"    {Names.Snake(member.Name).ToUpperInvariant()} = {member.EnumValue}\n");
                text.Append('\n');
                continue;
            }

            text.Append("@dataclass(frozen=True)\n");
            text.Append($"class {type.Name}:\n");
            if (type.Members.Count == 0)
                text.Append("    pass\n");
            foreach (var member in type.Members)
                text.Append($"    {PythonMember(member.Name)}: {PythonType(member.Type)}\n");
            text.Append('\n');
        }
        return text.ToString();
    }

    private static string EmitPythonStubs(RuneApiModel model) =>
        EmitPython(model);

    private static string EmitRust(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\n#[allow(unused_imports)]\n");
        text.Append("pub use crate::bindings::rune::api::types::{\n");
        foreach (var type in model.Types)
            text.Append($"    {type.Name},\n");
        text.Append("};\n");
        return text.ToString();
    }

    private static string EmitJson(RuneApiModel model)
    {
        var document = new
        {
            package = model.Package,
            version = model.Version,
            netCordVersion = model.NetCordVersion,
            fingerprint = model.Fingerprint,
            types = model.Types.Select(type => new
            {
                type.Name,
                type.NetCordName,
                type.IsEnum,
                type.Base,
                members = type.Members.Select(member => new
                {
                    member.Name,
                    member.CanonicalId,
                    type = member.Type.Name,
                    member.Type.Optional,
                    member.Representation,
                    member.EnumValue,
                    projections = new
                    {
                        javaScript = Names.Camel(member.Name),
                        python = PythonMember(member.Name),
                        rust = RustMember(member.Name)
                    }
                })
            }),
            events = model.Events
        };

        return JsonSerializer.Serialize(
                   document,
                   new JsonSerializerOptions
                   {
                       WriteIndented = true,
                       PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                   }) + "\n";
    }

    private static string EmitDocumentation(RuneApiModel model, string? language)
    {
        var text = new StringBuilder("<!-- <auto-generated by Rune.Api.Generator /> -->\n\n");
        text.Append(language is null ? "# Rune.API reference\n\n" : $"# Rune.API reference: {language}\n\n");
        text.Append($"API fingerprint: `{model.Fingerprint}`\n\n");
        text.Append("## Events\n\n");
        foreach (var gatewayEvent in model.Events)
            text.Append($"- `{gatewayEvent.Name}`: `{gatewayEvent.Payload}` (`{gatewayEvent.World}`)\n");
        text.Append("\n## Types\n\n");

        foreach (var type in model.Types)
        {
            text.Append($"### {type.Name}\n\n");
            text.Append($"NetCord: `{type.NetCordName}`\n\n");
            foreach (var member in type.Members)
            {
                var name = language switch
                {
                    "JavaScript" => Names.Camel(member.Name),
                    "Python" => PythonMember(member.Name),
                    "Rust" => RustMember(member.Name),
                    _ => member.Name
                };
                text.Append($"- `{name}` maps to `{member.CanonicalId}`\n");
            }
            text.Append('\n');
        }

        return text.ToString();
    }

    private static string WitType(RuneApiValueType type)
    {
        var value = type.IsSelectedType ? Names.Kebab(type.Name) : type.Name;
        return type.Optional ? $"option<{value}>" : value;
    }

    private static string CSharpType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "ulong",
            "bool" => "bool",
            "string" => "string",
            _ => type.Name
        };
        return type.Optional ? value + "?" : value;
    }

    private static string TypeScriptType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "bigint",
            "bool" => "boolean",
            "string" => "string",
            _ => type.Name
        };
        return type.Optional ? value + " | null" : value;
    }

    private static string PythonType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "int",
            "bool" => "bool",
            "string" => "str",
            _ => type.Name
        };
        return type.Optional ? value + " | None" : value;
    }

    private static string RustType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "u64",
            "bool" => "bool",
            "string" => "String",
            _ => type.Name
        };
        return type.Optional ? $"Option<{value}>" : value;
    }

    private static string PythonMember(string name)
    {
        var value = Names.Snake(name);
        return value == "type" ? "type_" : value;
    }

    private static string RustMember(string name)
    {
        var value = Names.Snake(name);
        return value == "type" ? "type_" : value;
    }
}
