using System.Text;
using System.Text.Json;

namespace Rune.Api.Generator;

public static class RuneApiEmitter
{
    private const string Header = "// <auto-generated by Rune.Api.Generator />\n";
    private static readonly string[] Languages =
    [
        "javascript",
        "typescript",
        "python",
        "ruby",
        "rust",
        "c",
        "cpp",
        "csharp"
    ];

    public static IReadOnlyDictionary<string, string> Emit(RuneApiModel model)
    {
        var output = new SortedDictionary<string, string>(StringComparer.Ordinal)
        {
            ["docs/api/generated/index.md"] = EmitDocumentation(model, null),
            ["generated/api/model.json"] = EmitJson(model),
            ["generated/api/rpc.json"] = EmitRpcJson(model),
            ["generated/javascript/rune-api.js"] = EmitJavaScript(model),
            ["generated/javascript/rune-api.d.ts"] = EmitTypeScriptDeclarations(model),
            ["generated/typescript/rune-api.ts"] = EmitTypeScript(model),
            ["generated/python/rune_api.py"] = EmitPython(model),
            ["generated/python/rune_api.pyi"] = EmitPythonStubs(model),
            ["generated/ruby/rune_api.rb"] = EmitRuby(model),
            ["generated/rust/rune_api.rs"] = EmitRust(model),
            ["generated/c/rune_api.h"] = EmitC(model),
            ["generated/cpp/rune_api.hpp"] = EmitCpp(model),
            ["generated/csharp/RuneApi.cs"] = EmitCSharpSdk(model),
            ["src/Rune.Bot/Api/Generated/NetCordRuneApi.g.cs"] = EmitNetCordProjection(model),
            ["src/Rune.Core/Api/Generated/RuneApi.g.cs"] = EmitManagedModel(model)
        };

        foreach (var language in Languages)
        {
            output[$"docs/api/generated/{language}.md"] =
                EmitDocumentation(model, language);
        }

        return output;
    }

    private static string EmitManagedModel(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\n#nullable enable\n\nnamespace Rune.Core.Api.Generated;\n\n");
        text.Append($"public static class RuneApiMetadata\n{{\n    public const string Fingerprint = \"{model.Fingerprint}\";\n}}\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"public enum {type.Name}\n{{\n");
                foreach (var member in type.Members)
                    text.Append($"    {member.Name} = {member.EnumValue},\n");
                text.Append("}\n\n");
                continue;
            }

            var members = AllMembers(model, type);
            text.Append($"public sealed record {type.Name}(\n");
            for (var index = 0; index < members.Count; index++)
            {
                var member = members[index];
                var suffix = index == members.Count - 1 ? ");" : ",";
                text.Append($"    {CSharpType(member.Type)} {member.Name}{suffix}\n");
            }
            if (members.Count == 0)
                text.Append(");\n");
            text.Append('\n');
        }

        text.Append("public enum RuneApiEvent\n{\n");
        for (var index = 0; index < model.Events.Count; index++)
            text.Append($"    {model.Events[index].Name} = {index},\n");
        text.Append("}\n");
        return text.ToString();
    }

    private static string EmitNetCordProjection(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\n#nullable enable\n\nusing RuneApi = Rune.Core.Api.Generated;\n\n");
        text.Append("namespace Rune.Bot.Api.Generated;\n\n");
        text.Append("public static class NetCordRuneApi\n{\n");

        foreach (var type in model.Types.Where(value => !value.IsEnum))
        {
            var members = AllMembers(model, type);
            text.Append($"    public static RuneApi.{type.Name} Project(\n");
            text.Append($"        {type.NetCordName} value) =>\n");
            text.Append("        new(\n");
            for (var index = 0; index < members.Count; index++)
            {
                var member = members[index];
                var suffix = index == members.Count - 1 ? ");" : ",";
                text.Append($"            {ProjectionExpression(member, $"value.{member.Name}")}{suffix}\n");
            }
            if (members.Count == 0)
                text.Append("        );\n");
            text.Append('\n');
        }

        text.Append("}\n\n");
        text.Append("public static class RuneApiHostCalls\n{\n");
        foreach (var type in model.Types)
        {
            foreach (var method in type.Methods)
            {
                text.Append(
                    $"    public const string {type.Name}{method.Name} = \"{method.CanonicalId}\";\n");
            }
        }
        text.Append("}\n");
        return text.ToString();
    }

    private static string ProjectionExpression(RuneApiMember member, string source)
    {
        if (!member.Type.IsSelectedType)
            return source;

        if (member.Type.Name == "ReactionType")
            return $"(RuneApi.ReactionType)(int){source}";

        return member.Type.Optional
            ? $"{source} is {{ }} selected ? Project(selected) : null"
            : $"Project({source})";
    }

    private static string EmitJavaScript(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\nlet __transport = null;\nconst __receivers = new WeakMap();\n\n");
        text.Append("export function __setRuneTransport(transport) { __transport = transport; }\n");
        text.Append("function __rpc() { if (!__transport) throw new Error(\"Rune RPC transport is not configured\"); return __transport; }\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"export const {type.Name} = Object.freeze({{\n");
                foreach (var member in type.Members)
                    text.Append($"    {Names.Camel(member.Name)}: {member.EnumValue},\n");
                text.Append("});\n\n");
                continue;
            }

            var inheritance = type.Base is null ? string.Empty : $" extends {type.Base}";
            text.Append($"export class {type.Name}{inheritance} {{\n");
            text.Append("    constructor(value = {}) {\n");
            if (type.Base is not null)
                text.Append("        super(value);\n");
            foreach (var member in type.Members)
            {
                var projected = Names.Camel(member.Name);
                var expression = JavaScriptHydrate(member.Type, $"value.{projected}");
                text.Append($"        this.{projected} = {expression};\n");
            }
            if (AllMethods(model, type).Count > 0)
                text.Append("        if (value.__runeReceiver != null) __receivers.set(this, value.__runeReceiver);\n");
            text.Append("    }\n");

            foreach (var method in type.Methods)
            {
                var name = Names.Camel(Names.WithoutAsync(method.Name));
                var parameters = string.Join(", ", method.Parameters.Select(value => Names.Camel(value.Name)));
                text.Append($"\n    async {name}({parameters}) {{\n");
                text.Append($"        const result = await __rpc().call(\"{method.CanonicalId}\", __receivers.get(this), {{\n");
                foreach (var parameter in method.Parameters)
                {
                    var parameterName = Names.Camel(parameter.Name);
                    text.Append($"            {parameterName}: {JavaScriptLower(parameter.Type, parameterName)},\n");
                }
                text.Append("        });\n");
                text.Append($"        return {JavaScriptHydrate(method.Result, "result")};\n");
                text.Append("    }\n");
            }

            text.Append("}\n\n");
        }

        text.Append("export const events = Object.freeze({\n");
        foreach (var gatewayEvent in model.Events)
            text.Append($"    {Names.Camel(gatewayEvent.Name)}: \"{gatewayEvent.Name}\",\n");
        text.Append("});\n");
        return text.ToString();
    }

    private static string EmitTypeScriptDeclarations(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\nexport interface RuneRpcTransport {\n    call(method: string, receiver: string | null | undefined, args: unknown): Promise<any>;\n}\n");
        text.Append("export declare function __setRuneTransport(transport: RuneRpcTransport): void;\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"export declare const {type.Name}: {{\n");
                foreach (var member in type.Members)
                    text.Append($"    readonly {Names.Camel(member.Name)}: {member.EnumValue};\n");
                text.Append("};\n\n");
                continue;
            }

            var inheritance = type.Base is null ? string.Empty : $" extends {type.Base}";
            text.Append($"export declare class {type.Name}{inheritance} {{\n");
            foreach (var member in type.Members)
                text.Append($"    readonly {Names.Camel(member.Name)}: {TypeScriptType(member.Type)};\n");
            text.Append("    constructor(value?: any);\n");
            foreach (var method in type.Methods)
            {
                var name = Names.Camel(Names.WithoutAsync(method.Name));
                var parameters = string.Join(", ", method.Parameters.Select(parameter =>
                    $"{Names.Camel(parameter.Name)}: {TypeScriptType(parameter.Type)}"));
                text.Append($"    {name}({parameters}): Promise<{TypeScriptType(method.Result)}>;\n");
            }
            text.Append("}\n\n");
        }
        return text.ToString();
    }

    private static string EmitTypeScript(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\nexport interface RuneRpcTransport {\n    call(method: string, receiver: string | null | undefined, args: unknown): Promise<any>;\n}\n\n");
        text.Append("let transport: RuneRpcTransport | null = null;\nconst receivers = new WeakMap<object, string>();\n");
        text.Append("export function __setRuneTransport(value: RuneRpcTransport): void { transport = value; }\n");
        text.Append("function rpc(): RuneRpcTransport { if (!transport) throw new Error(\"Rune RPC transport is not configured\"); return transport; }\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"export enum {type.Name} {{\n");
                foreach (var member in type.Members)
                    text.Append($"    {member.Name} = {member.EnumValue},\n");
                text.Append("}\n\n");
                continue;
            }

            var inheritance = type.Base is null ? string.Empty : $" extends {type.Base}";
            text.Append($"export class {type.Name}{inheritance} {{\n");
            foreach (var member in type.Members)
                text.Append($"    readonly {Names.Camel(member.Name)}: {TypeScriptType(member.Type)};\n");
            text.Append("\n    constructor(value: any = {}) {\n");
            if (type.Base is not null)
                text.Append("        super(value);\n");
            foreach (var member in type.Members)
            {
                var name = Names.Camel(member.Name);
                text.Append($"        this.{name} = {JavaScriptHydrate(member.Type, $"value.{name}")};\n");
            }
            if (AllMethods(model, type).Count > 0)
                text.Append("        if (value.__runeReceiver != null) receivers.set(this, value.__runeReceiver);\n");
            text.Append("    }\n");
            foreach (var method in type.Methods)
            {
                var name = Names.Camel(Names.WithoutAsync(method.Name));
                var parameters = string.Join(", ", method.Parameters.Select(parameter =>
                    $"{Names.Camel(parameter.Name)}: {TypeScriptType(parameter.Type)}"));
                text.Append($"\n    async {name}({parameters}): Promise<{TypeScriptType(method.Result)}> {{\n");
                text.Append($"        const result = await rpc().call(\"{method.CanonicalId}\", receivers.get(this), {{\n");
                foreach (var parameter in method.Parameters)
                {
                    var parameterName = Names.Camel(parameter.Name);
                    text.Append($"            {parameterName}: {JavaScriptLower(parameter.Type, parameterName)},\n");
                }
                text.Append("        });\n");
                text.Append($"        return {JavaScriptHydrate(method.Result, "result")};\n");
                text.Append("    }\n");
            }
            text.Append("}\n\n");
        }
        return text.ToString();
    }

    private static string EmitPython(RuneApiModel model)
    {
        var text = new StringBuilder("# <auto-generated by Rune.Api.Generator />\n\n");
        text.Append("from enum import IntEnum\n\n_transport = None\n\ndef __set_rune_transport(transport):\n    global _transport\n    _transport = transport\n\ndef _rpc():\n    if _transport is None:\n        raise RuntimeError(\"Rune RPC transport is not configured\")\n    return _transport\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"class {type.Name}(IntEnum):\n");
                foreach (var member in type.Members)
                    text.Append($"    {Names.Snake(member.Name).ToUpperInvariant()} = {member.EnumValue}\n");
                text.Append('\n');
                continue;
            }

            var inheritance = type.Base ?? "object";
            text.Append($"class {type.Name}({inheritance}):\n");
            text.Append("    def __init__(self, value=None):\n        value = value or {}\n");
            if (type.Base is not null)
                text.Append("        super().__init__(value)\n");
            foreach (var member in type.Members)
            {
                var name = PythonMember(member.Name);
                var expression = PythonHydrate(member.Type, $"value.get(\"{Names.Camel(member.Name)}\")");
                text.Append($"        self.{name} = {expression}\n");
            }
            if (AllMethods(model, type).Count > 0)
                text.Append("        self.__rune_receiver = value.get(\"__runeReceiver\")\n");
            if (type.Members.Count == 0 && type.Base is null && type.Methods.Count == 0)
                text.Append("        pass\n");

            foreach (var method in type.Methods)
            {
                var name = Names.Snake(Names.WithoutAsync(method.Name));
                var parameters = string.Join(", ", method.Parameters.Select(parameter => PythonMember(parameter.Name)));
                if (parameters.Length > 0)
                    parameters = ", " + parameters;
                text.Append($"\n    async def {name}(self{parameters}):\n");
                text.Append($"        result = await _rpc().call(\"{method.CanonicalId}\", self.__rune_receiver, {{\n");
                foreach (var parameter in method.Parameters)
                {
                    var parameterName = PythonMember(parameter.Name);
                    text.Append($"            \"{Names.Camel(parameter.Name)}\": {PythonLower(parameter.Type, parameterName)},\n");
                }
                text.Append("        })\n");
                text.Append($"        return {PythonHydrate(method.Result, "result")}\n");
            }
            text.Append('\n');
        }
        return text.ToString();
    }

    private static string EmitPythonStubs(RuneApiModel model)
    {
        var text = new StringBuilder("# <auto-generated by Rune.Api.Generator />\n\nfrom enum import IntEnum\nfrom typing import Any, Protocol\n\nclass RuneRpcTransport(Protocol):\n    async def call(self, method: str, receiver: str | None, args: Any) -> Any: ...\n\ndef __set_rune_transport(transport: RuneRpcTransport) -> None: ...\n\n");
        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"class {type.Name}(IntEnum):\n");
                foreach (var member in type.Members)
                    text.Append($"    {Names.Snake(member.Name).ToUpperInvariant()}: int\n");
                text.Append('\n');
                continue;
            }

            var inheritance = type.Base is null ? string.Empty : $"({type.Base})";
            text.Append($"class {type.Name}{inheritance}:\n");
            foreach (var member in type.Members)
                text.Append($"    {PythonMember(member.Name)}: {PythonType(member.Type)}\n");
            text.Append("    def __init__(self, value: Any = ...) -> None: ...\n");
            foreach (var method in type.Methods)
            {
                var parameters = string.Join(", ", method.Parameters.Select(parameter =>
                    $"{PythonMember(parameter.Name)}: {PythonType(parameter.Type)}"));
                if (parameters.Length > 0)
                    parameters = ", " + parameters;
                text.Append($"    async def {Names.Snake(Names.WithoutAsync(method.Name))}(self{parameters}) -> {PythonType(method.Result)}: ...\n");
            }
            text.Append('\n');
        }
        return text.ToString();
    }

    private static string EmitRuby(RuneApiModel model)
    {
        var text = new StringBuilder("# <auto-generated by Rune.Api.Generator />\n\nmodule RuneApi\n  @transport = nil\n\n  def self.__set_rune_transport(transport)\n    @transport = transport\n  end\n\n  def self.__rpc\n    raise \"Rune RPC transport is not configured\" if @transport.nil?\n    @transport\n  end\n\n");
        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"  module {type.Name}\n");
                foreach (var member in type.Members)
                    text.Append($"    {Names.Snake(member.Name).ToUpperInvariant()} = {member.EnumValue}\n");
                text.Append("  end\n\n");
                continue;
            }

            var inheritance = type.Base is null ? string.Empty : $" < {type.Base}";
            text.Append($"  class {type.Name}{inheritance}\n");
            var ownMembers = type.Members.Select(member => $":{Names.Snake(member.Name)}").ToArray();
            if (ownMembers.Length > 0)
                text.Append($"    attr_reader {string.Join(", ", ownMembers)}\n");
            text.Append("\n    def initialize(value = {})\n");
            if (type.Base is not null)
                text.Append("      super(value)\n");
            foreach (var member in type.Members)
            {
                var name = Names.Snake(member.Name);
                text.Append($"      @{name} = value[:{Names.Camel(member.Name)}] || value[\"{Names.Camel(member.Name)}\"]\n");
            }
            if (AllMethods(model, type).Count > 0)
                text.Append("      @__rune_receiver = value[:__runeReceiver] || value[\"__runeReceiver\"]\n");
            text.Append("    end\n");
            foreach (var method in type.Methods)
            {
                var parameters = string.Join(", ", method.Parameters.Select(parameter => Names.Snake(parameter.Name)));
                text.Append($"\n    def {Names.Snake(Names.WithoutAsync(method.Name))}({parameters})\n");
                text.Append($"      result = RuneApi.__rpc.call(\"{method.CanonicalId}\", @__rune_receiver, {{\n");
                foreach (var parameter in method.Parameters)
                    text.Append($"        {Names.Camel(parameter.Name)}: {Names.Snake(parameter.Name)},\n");
                text.Append("      })\n");
                text.Append($"      {RubyHydrate(method.Result, "result")}\n");
                text.Append("    end\n");
            }
            text.Append("  end\n\n");
        }
        text.Append("end\n");
        return text.ToString();
    }

    private static string EmitRust(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\n// The guest runtime provides rune_rpc_call. Transport details are not Rune.API.\nuse serde::{Deserialize, Serialize};\nuse serde_json::Value;\n\n");
        text.Append("pub trait RuneRpc {\n    fn call(&self, method: &str, receiver: Option<&str>, args: Value) -> Result<Value, String>;\n}\n\n");
        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append("#[derive(Clone, Copy, Debug, Deserialize, Serialize)]\n");
                text.Append($"pub enum {type.Name} {{\n");
                foreach (var member in type.Members)
                    text.Append($"    {member.Name} = {member.EnumValue},\n");
                text.Append("}\n\n");
                continue;
            }

            text.Append("#[derive(Clone, Debug, Deserialize, Serialize)]\n");
            text.Append($"pub struct {type.Name} {{\n");
            foreach (var member in AllMembers(model, type))
                text.Append($"    pub {RustMember(member.Name)}: {RustType(member.Type)},\n");
            if (AllMethods(model, type).Count > 0)
                text.Append("    #[serde(rename = \"__runeReceiver\", default)]\n    pub(crate) __rune_receiver: Option<String>,\n");
            text.Append("}\n\n");
            if (AllMethods(model, type).Count > 0)
            {
                text.Append($"impl {type.Name} {{\n");
                foreach (var method in AllMethods(model, type))
                {
                    var parameters = string.Join(", ", method.Parameters.Select(parameter =>
                        $"{RustMember(parameter.Name)}: {RustType(parameter.Type)}"));
                    if (parameters.Length > 0)
                        parameters = ", " + parameters;
                    text.Append($"    pub fn {Names.Snake(Names.WithoutAsync(method.Name))}(&self, rpc: &dyn RuneRpc{parameters}) -> Result<{RustType(method.Result)}, String> {{\n");
                    text.Append("        let mut args = serde_json::Map::new();\n");
                    foreach (var parameter in method.Parameters)
                    {
                        var parameterName = RustMember(parameter.Name);
                        text.Append($"        args.insert(\"{Names.Camel(parameter.Name)}\".into(), serde_json::to_value({parameterName}).map_err(|error| error.to_string())?);\n");
                    }
                    text.Append($"        let value = rpc.call(\"{method.CanonicalId}\", self.__rune_receiver.as_deref(), Value::Object(args))?;\n");
                    text.Append("        serde_json::from_value(value).map_err(|error| error.to_string())\n");
                    text.Append("    }\n");
                }
                text.Append("}\n\n");
            }
        }
        return text.ToString();
    }

    private static string EmitC(RuneApiModel model)
    {
        var text = new StringBuilder("/* <auto-generated by Rune.Api.Generator /> */\n#pragma once\n\n#include <stdbool.h>\n#include <stdint.h>\n\ntypedef struct rune_rpc_transport rune_rpc_transport;\n\n");
        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"typedef enum rune_{Names.Snake(type.Name)} {{\n");
                foreach (var member in type.Members)
                    text.Append($"    RUNE_{Names.Snake(type.Name).ToUpperInvariant()}_{Names.Snake(member.Name).ToUpperInvariant()} = {member.EnumValue},\n");
                text.Append($"}} rune_{Names.Snake(type.Name)};\n\n");
                continue;
            }

            text.Append($"typedef struct rune_{Names.Snake(type.Name)} {{\n");
            foreach (var member in AllMembers(model, type))
                text.Append($"    {CType(member.Type)} {Names.Snake(member.Name)};\n");
            if (AllMethods(model, type).Count > 0)
                text.Append("    const char *__rune_receiver;\n");
            text.Append($"}} rune_{Names.Snake(type.Name)};\n\n");
        }

        foreach (var type in model.Types)
        {
            foreach (var method in AllMethods(model, type))
            {
                var function = $"rune_{Names.Snake(type.Name)}_{Names.Snake(Names.WithoutAsync(method.Name))}";
                text.Append($"int {function}(rune_rpc_transport *rpc, const rune_{Names.Snake(type.Name)} *self");
                foreach (var parameter in method.Parameters)
                    text.Append($", {CType(parameter.Type)} {Names.Snake(parameter.Name)}");
                text.Append($", {CType(method.Result)} *result);\n");
            }
        }
        return text.ToString();
    }

    private static string EmitCpp(RuneApiModel model)
    {
        var text = new StringBuilder("// <auto-generated by Rune.Api.Generator />\n#pragma once\n\n#include <cstdint>\n#include <optional>\n#include <string>\n\nnamespace rune {\nclass RpcTransport;\n\n");
        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"enum class {type.Name} {{\n");
                foreach (var member in type.Members)
                    text.Append($"    {member.Name} = {member.EnumValue},\n");
                text.Append("};\n\n");
                continue;
            }

            var inheritance = type.Base is null ? string.Empty : $" : public {type.Base}";
            text.Append($"class {type.Name}{inheritance} {{\npublic:\n");
            foreach (var member in type.Members)
                text.Append($"    {CppType(member.Type)} {Names.Snake(member.Name)};\n");
            foreach (var method in type.Methods)
            {
                var parameters = string.Join(", ", method.Parameters.Select(parameter =>
                    $"const {CppType(parameter.Type)}& {Names.Snake(parameter.Name)}"));
                if (parameters.Length > 0)
                    parameters = ", " + parameters;
                text.Append($"    {CppType(method.Result)} {Names.Snake(Names.WithoutAsync(method.Name))}(RpcTransport& rpc{parameters}) const;\n");
            }
            text.Append("};\n\n");
        }
        text.Append("} // namespace rune\n");
        return text.ToString();
    }

    private static string EmitCSharpSdk(RuneApiModel model)
    {
        var text = new StringBuilder(Header);
        text.Append("\n#nullable enable\n\nnamespace Rune.Api;\n\npublic interface IRuneRpcTransport\n{\n    Task<T> CallAsync<T>(string method, string? receiver, object arguments);\n}\n\n");
        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append($"public enum {type.Name}\n{{\n");
                foreach (var member in type.Members)
                    text.Append($"    {member.Name} = {member.EnumValue},\n");
                text.Append("}\n\n");
                continue;
            }

            var inheritance = type.Base is null ? string.Empty : $" : {type.Base}";
            text.Append($"public class {type.Name}{inheritance}\n{{\n");
            if (AllMethods(model, type).Count > 0)
                text.Append("    internal string? RuneReceiver { get; init; }\n");
            foreach (var member in type.Members)
                text.Append($"    public {CSharpType(member.Type)} {member.Name} {{ get; init; }}{CSharpDefault(member.Type)}\n");
            foreach (var method in type.Methods)
            {
                var parameters = string.Join(", ", method.Parameters.Select(parameter =>
                    $"{CSharpType(parameter.Type)} {parameter.Name}"));
                if (parameters.Length > 0)
                    parameters += ", ";
                text.Append($"\n    public Task<{CSharpType(method.Result)}> {method.Name}({parameters}IRuneRpcTransport rpc) =>\n");
                text.Append($"        rpc.CallAsync<{CSharpType(method.Result)}>(\"{method.CanonicalId}\", RuneReceiver, new {{ ");
                text.Append(string.Join(", ", method.Parameters.Select(parameter => parameter.Name)));
                text.Append(" });\n");
            }
            text.Append("}\n\n");
        }
        return text.ToString();
    }

    private static string EmitJson(RuneApiModel model)
    {
        var document = new
        {
            package = model.Package,
            version = model.Version,
            netCordVersion = model.NetCordVersion,
            fingerprint = model.Fingerprint,
            types = model.Types.Select(type => new
            {
                type.Name,
                type.NetCordName,
                type.IsEnum,
                type.Base,
                members = type.Members.Select(member => new
                {
                    member.Name,
                    member.CanonicalId,
                    type = member.Type.Name,
                    member.Type.Optional,
                    member.Representation,
                    member.EnumValue
                }),
                methods = type.Methods.Select(method => new
                {
                    method.Name,
                    method.CanonicalId,
                    method.IsAsync,
                    parameters = method.Parameters,
                    result = method.Result
                })
            }),
            events = model.Events
        };

        return JsonSerializer.Serialize(
                   document,
                   new JsonSerializerOptions
                   {
                       WriteIndented = true,
                       PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                   }) + "\n";
    }

    private static string EmitRpcJson(RuneApiModel model)
    {
        var calls = model.Types.SelectMany(type =>
            type.Methods.Select(method => new
            {
                id = method.CanonicalId,
                receiver = type.Name,
                asynchronous = method.IsAsync,
                parameters = method.Parameters.Select(parameter => new
                {
                    parameter.Name,
                    type = parameter.Type.Name,
                    parameter.Type.Optional
                }),
                result = new
                {
                    type = method.Result.Name,
                    method.Result.Optional
                }
            }));
        return JsonSerializer.Serialize(
                   new
                   {
                       apiVersion = model.Version,
                       model.Fingerprint,
                       transport = "microvm-rpc",
                       calls
                   },
                   new JsonSerializerOptions
                   {
                       WriteIndented = true,
                       PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                   }) + "\n";
    }

    private static string EmitDocumentation(RuneApiModel model, string? language)
    {
        var text = new StringBuilder("<!-- <auto-generated by Rune.Api.Generator /> -->\n\n");
        var title = language is null ? "Rune.API reference" : $"Rune.API reference: {DisplayLanguage(language)}";
        text.Append($"# {title}\n\n");
        text.Append($"API `{model.Version}` · NetCord `{model.NetCordVersion}` · fingerprint `{model.Fingerprint}`\n\n");
        text.Append("Rune.API is a selected snapshot and method projection of NetCord. The initial surface does not expose fetching, arbitrary channel access, guild management, the Discord client, caches or general REST access.\n\n");
        text.Append("## Events\n\n");
        foreach (var gatewayEvent in model.Events)
            text.Append($"- `{gatewayEvent.Name}` receives `{gatewayEvent.Payload}` from `{gatewayEvent.NetCordName}`.\n");
        text.Append("\n## Types\n\n");

        foreach (var type in model.Types)
        {
            text.Append($"### {type.Name}\n\n");
            text.Append($"NetCord: `{type.NetCordName}`");
            if (type.Base is not null)
                text.Append($" · inherits `{type.Base}`");
            text.Append("\n\n");
            foreach (var member in type.Members)
                text.Append($"- `{ProjectedMember(member.Name, language)}` → `{member.CanonicalId}`\n");
            foreach (var method in type.Methods)
                text.Append($"- `{ProjectedMethod(method, language)}` → `{method.CanonicalId}`\n");
            text.Append('\n');
        }
        return text.ToString();
    }

    private static IReadOnlyList<RuneApiMember> AllMembers(RuneApiModel model, RuneApiType type)
    {
        var members = new List<RuneApiMember>();
        if (type.Base is not null)
        {
            var baseType = model.Types.Single(value => value.Name == type.Base);
            members.AddRange(AllMembers(model, baseType));
        }
        members.AddRange(type.Members);
        return members;
    }

    private static IReadOnlyList<RuneApiMethod> AllMethods(RuneApiModel model, RuneApiType type)
    {
        var methods = new List<RuneApiMethod>();
        if (type.Base is not null)
        {
            var baseType = model.Types.Single(value => value.Name == type.Base);
            methods.AddRange(AllMethods(model, baseType));
        }
        methods.AddRange(type.Methods);
        return methods;
    }

    private static string JavaScriptHydrate(RuneApiValueType type, string value)
    {
        if (type.Optional)
            return $"{value} == null ? null : {JavaScriptHydrate(type with { Optional = false }, value)}";
        if (type.IsSelectedType && type.Name != "ReactionType")
            return $"new {type.Name}({value})";
        if (type.Name == "u64")
            return $"BigInt({value})";
        return value;
    }

    private static string JavaScriptLower(RuneApiValueType type, string value)
    {
        if (!type.IsSelectedType || type.Name == "ReactionType")
            return value;
        var target = type.Name;
        return $"Object.fromEntries(Object.entries({value}).filter(([key]) => !key.startsWith(\"__rune\"))) /* {target} */";
    }

    private static string PythonHydrate(RuneApiValueType type, string value)
    {
        if (type.Optional)
            return $"None if {value} is None else {PythonHydrate(type with { Optional = false }, value)}";
        if (type.IsSelectedType && type.Name != "ReactionType")
            return $"{type.Name}({value})";
        return value;
    }

    private static string PythonLower(RuneApiValueType type, string value) => value;

    private static string RubyHydrate(RuneApiValueType type, string value)
    {
        if (type.IsSelectedType && type.Name != "ReactionType")
            return $"{type.Name}.new({value})";
        return value;
    }

    private static string CSharpType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "ulong",
            "bool" => "bool",
            "string" => "string",
            _ => type.Name
        };
        return type.Optional ? value + "?" : value;
    }

    private static string CSharpDefault(RuneApiValueType type) =>
        !type.Optional && (type.Name == "string" || type.IsSelectedType && type.Name != "ReactionType")
            ? " = default!;"
            : string.Empty;

    private static string TypeScriptType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "bigint",
            "bool" => "boolean",
            "string" => "string",
            _ => type.Name
        };
        return type.Optional ? value + " | null" : value;
    }

    private static string PythonType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "int",
            "bool" => "bool",
            "string" => "str",
            _ => type.Name
        };
        return type.Optional ? value + " | None" : value;
    }

    private static string RustType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "u64",
            "bool" => "bool",
            "string" => "String",
            _ => type.Name
        };
        return type.Optional ? $"Option<{value}>" : value;
    }

    private static string CType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "uint64_t",
            "bool" => "bool",
            "string" => "const char *",
            _ => $"rune_{Names.Snake(type.Name)}"
        };
        return type.Optional && type.Name is not "string" ? value : value;
    }

    private static string CppType(RuneApiValueType type)
    {
        var value = type.Name switch
        {
            "u64" => "std::uint64_t",
            "bool" => "bool",
            "string" => "std::string",
            _ => type.Name
        };
        return type.Optional ? $"std::optional<{value}>" : value;
    }

    private static string PythonMember(string name)
    {
        var value = Names.Snake(name);
        return value == "type" ? "type_" : value;
    }

    private static string RustMember(string name)
    {
        var value = Names.Snake(name);
        return value == "type" ? "type_" : value;
    }

    private static string ProjectedMember(string name, string? language) =>
        language switch
        {
            "javascript" or "typescript" => Names.Camel(name),
            "python" or "ruby" or "rust" or "c" or "cpp" => Names.Snake(name),
            _ => name
        };

    private static string ProjectedMethod(RuneApiMethod method, string? language)
    {
        var name = language switch
        {
            "csharp" => method.Name,
            "javascript" or "typescript" => Names.Camel(Names.WithoutAsync(method.Name)),
            _ => Names.Snake(Names.WithoutAsync(method.Name))
        };
        var parameters = string.Join(", ", method.Parameters.Select(parameter => ProjectedMember(parameter.Name, language)));
        return $"{name}({parameters})";
    }

    private static string DisplayLanguage(string language) =>
        language switch
        {
            "javascript" => "JavaScript",
            "typescript" => "TypeScript",
            "python" => "Python",
            "ruby" => "Ruby",
            "rust" => "Rust",
            "c" => "C",
            "cpp" => "C++",
            "csharp" => "C#",
            _ => language
        };
}
