using System.Text;

namespace Rune.Generator;

public static class RuneApiEmitter
{
    public static IReadOnlyDictionary<string, string>
        Emit(RuneApiModel model)
    {
        var output =
            new SortedDictionary<string, string>(
                StringComparer.Ordinal)
            {
                ["generated/rust/rune_api.rs"] =
                    EmitRust(model),

                ["generated/javascript/rune-api.js"] =
                    EmitJavaScript(model),

                ["generated/typescript/rune-api.ts"] =
                    EmitTypeScript(model)
            };

        foreach (var item in
                 RuneApiCSharpEmitter.Emit(model))
        {
            output[item.Key] = item.Value;
        }

        return output;
    }

    private static string EmitJavaScript(
        RuneApiModel model)
    {
        var text =
            new StringBuilder(
                "// <auto-generated by Rune.Api.Generator />\n" +
                "// @ts-check\n\n");

        var hostMethods =
            model.Types
                .SelectMany(
                    type =>
                        type.Methods)
                .ToArray();

        text.Append(
            "class RuneHost {\n" +
            "    /**\n");

        foreach (var method in hostMethods)
        {
            var callback =
                TypeScriptHostCallbackName(
                    method.HostName);

            text.Append(
                $"     * @param {{function({JavaScriptFunctionParameters(method, model)}): Promise<{JavaScriptType(method.Result)}>}} [{callback}]\n");
        }

        text.Append(
            "     */\n" +
            "    constructor(\n");

        foreach (var method in hostMethods)
        {
            var callback =
                TypeScriptHostCallbackName(
                    method.HostName);

            text.Append(
                $"        {callback} = async () => {{ throw new Error(\"Rune host is not configured\"); }},\n");
        }

        text.Append("    ) {\n");

        foreach (var method in hostMethods)
        {
            var callback =
                TypeScriptHostCallbackName(
                    method.HostName);

            text.Append(
                $"        this.{callback} = {callback};\n");
        }

        text.Append(
            "    }\n" +
            "}\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append(
                    $"const {type.Name} = {{\n");

                foreach (var member in type.Members)
                {
                    text.Append(
                        $"    {member.Name}: {member.EnumValue},\n");
                }

                text.Append("};\n\n");
                continue;
            }

            var inheritance =
                type.Base is null
                    ? string.Empty
                    : $" extends {type.Base}";

            text.Append(
                $"class {type.Name}{inheritance} {{\n");

            foreach (var member in type.Members)
            {
                text.Append(
                    $"    /** @type {{{JavaScriptType(member.Type)}}} */\n" +
                    $"    {Camel(member.Name)};\n");
            }

            text.Append(
                $"    /**\n" +
                $"     * @param {{{JavaScriptObjectType(type, model)}}} value\n" +
                "     * @param {RuneHost} [__host]\n" +
                "     */\n" +
                "    constructor(value, __host = new RuneHost()) {\n");

            if (type.Base is not null)
            {
                text.Append(
                    "        super(value, __host);\n");
            }
            else
            {
                text.Append(
                    "        this.__host = __host;\n");
            }

            foreach (var member in type.Members)
            {
                var name =
                    Camel(member.Name);

                text.Append(
                    $"        this.{name} = " +
                    $"{JavaScriptHydrate(member.Type, $"value.{name}", model)};\n");
            }

            text.Append("    }\n");

            foreach (var method in type.Methods)
            {
                var name =
                    Camel(WithoutAsync(method.Name));

                text.Append("    /**\n");

                foreach (var parameter in method.Parameters)
                {
                    text.Append(
                        $"     * @param {{{JavaScriptInputType(parameter.Type, model)}}} {Camel(parameter.Name)}\n");
                }

                text.Append(
                    $"     * @returns {{Promise<{JavaScriptType(method.Result)}>}}\n" +
                    "     */\n");

                var parameters =
                    string.Join(
                        ", ",
                        method.Parameters.Select(
                            parameter =>
                                Camel(parameter.Name)));

                text.Append(
                    $"    async {name}({parameters}) {{\n" +
                    $"        const result = await this.__host.{TypeScriptHostCallbackName(method.HostName)}(");

                text.Append(
                    string.Join(
                        ", ",
                        method.Parameters.Select(
                            parameter =>
                                Camel(parameter.Name))));

                text.Append(
                    ");\n" +
                    $"        return {JavaScriptHydrate(method.Result, "result", model)};\n" +
                    "    }\n");
            }

            text.Append("}\n\n");
        }

        foreach (var type in model.Types)
        {
            foreach (var method in type.Methods)
            {
                text.Append(
                    $"const {Constant(type.Name, method.Name)} = " +
                    $"{{ host: \"{method.HostName}\", " +
                    $"netCord: \"{method.CanonicalId}\" }};\n");
            }
        }

        return text.ToString();
    }

    private static string JavaScriptHydrate(
        RuneApiValueType type,
        string value,
        RuneApiModel model)
    {
        if (type.Optional)
        {
            return
                $"{value} == null ? null : " +
                JavaScriptHydrate(
                    type with { Optional = false },
                    value,
                    model);
        }

        if (type.Name == "u64")
            return $"String({value})";

        if (type.IsSelectedType &&
            !model.Types.Single(
                    item =>
                        item.Name == type.Name)
                .IsEnum)
        {
            return
                $"new {type.Name}({value}, this.__host)";
        }

        return value;
    }

    private static string JavaScriptFunctionParameters(
        RuneApiMethod method,
        RuneApiModel model) =>
        string.Join(
            ", ",
            method.Parameters.Select(
                parameter =>
                    JavaScriptInputType(
                        parameter.Type,
                        model)));

    private static string JavaScriptObjectType(
        RuneApiType type,
        RuneApiModel model) =>
        "{ " +
        string.Join(
            ", ",
            AllMembers(
                model,
                type)
                .Select(
                    member =>
                        $"{Camel(member.Name)}: {JavaScriptInputType(member.Type, model)}")) +
        " }";

    private static string JavaScriptInputType(
        RuneApiValueType type,
        RuneApiModel model)
    {
        if (type.Optional)
        {
            return
                "(" +
                JavaScriptInputType(
                    type with { Optional = false },
                    model) +
                "|null)";
        }

        if (type.IsSelectedType)
        {
            var selected =
                model.Types.Single(
                    item =>
                        item.Name == type.Name);

            if (!selected.IsEnum)
                return JavaScriptObjectType(selected, model);
        }

        return JavaScriptType(type);
    }

    private static string JavaScriptType(
        RuneApiValueType type)
    {
        var value =
            type.Name switch
            {
                "u64" => "string",
                "bool" => "boolean",
                "string" => "string",
                _ => type.Name
            };

        return type.Optional
            ? $"({value}|null)"
            : value;
    }

    private static string EmitTypeScript(
        RuneApiModel model)
    {
        var text =
            new StringBuilder(
                "// <auto-generated by Rune.Api.Generator />\n\n");

        text.Append(
            "export class RuneHost {\n");

        var hostMethods =
            model.Types
                .SelectMany(
                    type =>
                        type.Methods)
                .ToArray();

        foreach (var method in hostMethods)
        {
            var callback =
                TypeScriptHostCallbackName(
                    method.HostName);

            var parameters =
                string.Join(
                    ", ",
                    method.Parameters.Select(
                        parameter =>
                            $"{Camel(parameter.Name)}: " +
                            TypeScriptInputType(
                                parameter.Type,
                                model)));

            text.Append(
                $"    readonly {callback}: ({parameters}) => " +
                $"Promise<{TypeScriptType(method.Result)}>;\n");
        }

        text.Append("\n    constructor(\n");

        foreach (var method in hostMethods)
        {
            var callback =
                TypeScriptHostCallbackName(
                    method.HostName);

            var parameters =
                string.Join(
                    ", ",
                    method.Parameters.Select(
                        parameter =>
                            $"{Camel(parameter.Name)}: " +
                            TypeScriptInputType(
                                parameter.Type,
                                model)));

            text.Append(
                $"        {callback}: ({parameters}) => " +
                $"Promise<{TypeScriptType(method.Result)}> =\n" +
                "            async () => { throw new Error(\"Rune host is not configured\"); },\n");
        }

        text.Append("    ) {\n");

        foreach (var method in hostMethods)
        {
            var callback =
                TypeScriptHostCallbackName(
                    method.HostName);

            text.Append(
                $"        this.{callback} = {callback};\n");
        }

        text.Append(
            "    }\n" +
            "}\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.Append(
                    $"export enum {type.Name} {{\n");

                foreach (var member in type.Members)
                {
                    text.Append(
                        $"    {member.Name} = {member.EnumValue},\n");
                }

                text.Append("}\n\n");
                continue;
            }

            var inheritance =
                type.Base is null
                    ? string.Empty
                    : $" extends {type.Base}";

            text.Append(
                $"export class {type.Name}{inheritance} {{\n");

            foreach (var member in type.Members)
            {
                text.Append(
                    $"    readonly {Camel(member.Name)}: " +
                    $"{TypeScriptType(member.Type)};\n");
            }

            var hostParameter =
                type.Base is null
                    ? "protected readonly __host: RuneHost = new RuneHost()"
                    : "__host: RuneHost = new RuneHost()";

            text.Append(
                "\n    constructor(value: " +
                TypeScriptInputType(
                    new RuneApiValueType(
                        type.Name,
                        false,
                        true),
                    model) +
                ", " +
                hostParameter +
                ") {\n");

            if (type.Base is not null)
            {
                text.Append(
                    "        super(value, __host);\n");
            }

            foreach (var member in type.Members)
            {
                var name =
                    Camel(member.Name);

                text.Append(
                    $"        this.{name} = " +
                    $"{TypeScriptHydrate(member.Type, $"value.{name}", model)};\n");
            }

            text.Append("    }\n");

            foreach (var method in type.Methods)
            {
                EmitTypeScriptMethod(
                    text,
                    method,
                    model);
            }

            text.Append("}\n\n");
        }

        text.Append(
            "export interface RuneEventArguments {\n");

        foreach (var runeEvent in model.Events)
        {
            text.Append(
                $"    {runeEvent.Name}: {runeEvent.Payload};\n");
        }

        text.Append("}\n\n");

        foreach (var type in model.Types)
        {
            foreach (var method in type.Methods)
            {
                text.Append(
                    $"export const {Constant(type.Name, method.Name)} = " +
                    $"{{ host: \"{method.HostName}\", " +
                    $"netCord: \"{method.CanonicalId}\" }} as const;\n");
            }
        }

        return text.ToString();
    }

    private static void EmitTypeScriptMethod(
        StringBuilder text,
        RuneApiMethod method,
        RuneApiModel model)
    {
        var name =
            Camel(WithoutAsync(method.Name));

        var parameters =
            string.Join(
                ", ",
                method.Parameters.Select(
                    parameter =>
                        $"{Camel(parameter.Name)}: " +
                        TypeScriptInputType(
                            parameter.Type,
                            model)));

        text.Append(
            $"\n    async {name}({parameters}): " +
            $"Promise<{TypeScriptType(method.Result)}> {{\n");

        text.Append(
            $"        const result = await this.__host." +
            $"{TypeScriptHostCallbackName(method.HostName)}(");

        text.Append(
            string.Join(
                ", ",
                method.Parameters.Select(
                    parameter =>
                        TypeScriptLower(
                            parameter.Type,
                            Camel(parameter.Name)))));

        text.Append(
            ");\n");

        text.Append(
            $"        return {TypeScriptHydrate(method.Result, "result", model)};\n");

        text.Append("    }\n");
    }

    private static string TypeScriptHydrate(
        RuneApiValueType type,
        string value,
        RuneApiModel model)
    {
        if (type.Optional)
        {
            return
                $"{value} == null ? null : " +
                TypeScriptHydrate(
                    type with { Optional = false },
                    value,
                    model);
        }

        if (type.Name == "u64")
            return $"String({value})";

        if (type.IsSelectedType &&
            !model.Types.Single(
                    item =>
                        item.Name == type.Name)
                .IsEnum)
        {
            return
                $"new {type.Name}({value}, this.__host)";
        }

        return value;
    }

    private static string TypeScriptLower(
        RuneApiValueType type,
        string value)
    {
        if (type.Name == "u64")
            return value;

        if (type.IsSelectedType)
        {
            return value;
        }

        return value;
    }

    private static string TypeScriptInputType(
        RuneApiValueType type,
        RuneApiModel model)
    {
        if (type.Optional)
        {
            return
                TypeScriptInputType(
                    type with { Optional = false },
                    model) +
                " | null";
        }

        if (type.IsSelectedType)
        {
            var selected =
                model.Types.Single(
                    item =>
                        item.Name == type.Name);

            if (!selected.IsEnum)
            {
                return
                    "{ " +
                    string.Join(
                        "; ",
                        AllMembers(
                            model,
                            selected)
                        .Select(
                            member =>
                                $"{Camel(member.Name)}: " +
                                TypeScriptInputType(
                                    member.Type,
                                    model))) +
                    " }";
            }
        }

        return TypeScriptType(type);
    }

    private static string TypeScriptType(
        RuneApiValueType type)
    {
        var value =
            type.Name switch
            {
                "u64" => "string",
                "bool" => "boolean",
                "string" => "string",
                _ => type.Name
            };

        return type.Optional
            ? value + " | null"
            : value;
    }

    private static string EmitRust(
        RuneApiModel model)
    {
        var text =
            new StringBuilder(
                "// <auto-generated by Rune.Api.Generator />\n\n" +
                "mod rune_snowflake_serde {\n" +
                "    use serde::{Deserialize, Deserializer, Serializer};\n" +
                "    pub fn serialize<S: Serializer>(value: &u64, serializer: S) -> Result<S::Ok, S::Error> {\n" +
                "        serializer.serialize_str(&value.to_string())\n" +
                "    }\n" +
                "    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<u64, D::Error> {\n" +
                "        let value = String::deserialize(deserializer)?;\n" +
                "        value.parse().map_err(serde::de::Error::custom)\n" +
                "    }\n" +
                "}\n\n" +
                "mod rune_optional_snowflake_serde {\n" +
                "    use serde::{Deserialize, Deserializer, Serializer};\n" +
                "    pub fn serialize<S: Serializer>(value: &Option<u64>, serializer: S) -> Result<S::Ok, S::Error> {\n" +
                "        match value {\n" +
                "            Some(value) => serializer.serialize_some(&value.to_string()),\n" +
                "            None => serializer.serialize_none(),\n" +
                "        }\n" +
                "    }\n" +
                "    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Option<u64>, D::Error> {\n" +
                "        let value = Option::<String>::deserialize(deserializer)?;\n" +
                "        value.map(|value| value.parse().map_err(serde::de::Error::custom)).transpose()\n" +
                "    }\n" +
                "}\n\n");

        foreach (var type in model.Types)
        {
            if (!type.IsEnum)
                continue;

            text.Append(
                "#[derive(Clone, Copy, Debug, PartialEq, Eq, serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]\n" +
                "#[repr(i32)]\n" +
                $"pub enum {type.Name} {{\n");

            foreach (var member in type.Members)
            {
                text.Append(
                    $"    {member.Name} = {member.EnumValue},\n");
            }

            text.Append("}\n\n");
        }

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
                continue;

            text.Append(
                "#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]\n" +
                "#[serde(rename_all = \"camelCase\")]\n" +
                $"pub struct {type.Name} {{\n");

            foreach (var member in AllMembers(
                         model,
                         type))
            {
                if (member.Representation == "snowflake")
                {
                    text.Append(
                        member.Type.Optional
                            ? "    #[serde(with = \"rune_optional_snowflake_serde\")]\n"
                            : "    #[serde(with = \"rune_snowflake_serde\")]\n");
                }

                text.Append(
                    $"    pub {RustMember(member.Name)}: " +
                    $"{RustType(member.Type)},\n");
            }

            text.Append("}\n\n");
        }

        text.Append(
            "pub trait RuneHost {\n");

        foreach (var pair in
                 model.Types.SelectMany(
                     type =>
                         type.Methods.Select(
                             method =>
                                 (Type: type, Method: method))))
        {
            var method =
                pair.Method;

            var parameters =
                string.Join(
                    ", ",
                    method.Parameters.Select(
                        parameter =>
                            $"{RustMember(parameter.Name)}: " +
                            $"&{RustReferenceType(parameter.Type)}"));

            if (parameters.Length > 0)
                parameters = ", " + parameters;

            text.Append(
                $"    fn {HostMethodName(method.HostName)}(" +
                $"&mut self{parameters}) -> " +
                $"Result<{RustType(method.Result)}, String>;\n");
        }

        text.Append("}\n\n");

        text.Append(
            "thread_local! {\n" +
            "    static __RUNE_HOST: std::cell::RefCell<Option<Box<dyn RuneHost>>> =\n" +
            "        std::cell::RefCell::new(None);\n" +
            "}\n\n" +
            "pub fn __rune_install_host(host: Box<dyn RuneHost>) {\n" +
            "    __RUNE_HOST.with(|slot| {\n" +
            "        *slot.borrow_mut() = Some(host);\n" +
            "    });\n" +
            "}\n\n" +
            "fn __rune_with_host<T>(\n" +
            "    callback: impl FnOnce(&mut dyn RuneHost) -> Result<T, String>,\n" +
            ") -> Result<T, String> {\n" +
            "    __RUNE_HOST.with(|slot| {\n" +
            "        let mut slot = slot.borrow_mut();\n" +
            "        let host = slot\n" +
            "            .as_deref_mut()\n" +
            "            .ok_or_else(|| \"Rune host is not configured\".to_string())?;\n" +
            "        callback(host)\n" +
            "    })\n" +
            "}\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
                continue;

            var methods =
                AllMethods(
                    model,
                    type);

            if (methods.Count == 0)
                continue;

            text.Append(
                $"impl {type.Name} {{\n");

            foreach (var method in methods)
            {
                var parameters =
                    string.Join(
                        ", ",
                        method.Parameters.Select(
                            parameter =>
                                $"{RustMember(parameter.Name)}: " +
                                RustType(parameter.Type)));

                if (parameters.Length > 0)
                    parameters = ", " + parameters;

                text.Append(
                    $"    pub fn {Snake(WithoutAsync(method.Name))}(" +
                    $"&self{parameters}) -> " +
                    $"Result<{RustType(method.Result)}, String> {{\n");

                text.Append(
                    "        __rune_with_host(|host| " +
                    $"host.{HostMethodName(method.HostName)}(");

                text.Append(
                    string.Join(
                        ", ",
                        method.Parameters.Select(
                            parameter =>
                                $"&{RustMember(parameter.Name)}")));

                text.Append("))\n    }\n");
            }

            text.Append("}\n\n");
        }

        text.Append(
            "#[derive(Clone, Debug, PartialEq)]\n" +
            "pub enum RuneEventArguments {\n");

        foreach (var runeEvent in model.Events)
        {
            text.Append(
                $"    {runeEvent.Name}({runeEvent.Payload}),\n");
        }

        text.Append("}\n\n");

        foreach (var type in model.Types)
        {
            foreach (var method in type.Methods)
            {
                text.Append(
                    $"pub const {Constant(type.Name, method.Name)}_HOST: &str = " +
                    $"\"{method.HostName}\";\n");

                text.Append(
                    $"pub const {Constant(type.Name, method.Name)}_NETCORD: &str = " +
                    $"\"{method.CanonicalId}\";\n");
            }
        }

        return text.ToString();
    }

    internal static string TypeScriptTypeForDocumentation(
        RuneApiValueType type) =>
        TypeScriptType(type);

    internal static string RustTypeForDocumentation(
        RuneApiValueType type) =>
        RustType(type);

    internal static string TypeScriptMemberForDocumentation(
        string name) =>
        Camel(name);

    internal static string RustMemberForDocumentation(
        string name) =>
        RustMember(name);

    internal static string TypeScriptMethodForDocumentation(
        string name) =>
        Camel(WithoutAsync(name));

    internal static string RustMethodForDocumentation(
        string name) =>
        Snake(WithoutAsync(name));

    internal static IReadOnlyList<RuneApiMember>
        MembersForDocumentation(
            RuneApiModel model,
            RuneApiType type) =>
        AllMembers(model, type);

    internal static IReadOnlyList<RuneApiMethod>
        MethodsForDocumentation(
            RuneApiModel model,
            RuneApiType type) =>
        AllMethods(model, type);

    private static IReadOnlyList<RuneApiMember>
        AllMembers(
            RuneApiModel model,
            RuneApiType type)
    {
        var members =
            new List<RuneApiMember>();

        if (type.Base is not null)
        {
            var baseType =
                model.Types.Single(
                    value =>
                        value.Name == type.Base);

            members.AddRange(
                AllMembers(
                    model,
                    baseType));
        }

        members.AddRange(
            type.Members);

        return members;
    }

    private static IReadOnlyList<RuneApiMethod>
        AllMethods(
            RuneApiModel model,
            RuneApiType type)
    {
        var methods =
            new List<RuneApiMethod>();

        if (type.Base is not null)
        {
            var baseType =
                model.Types.Single(
                    value =>
                        value.Name == type.Base);

            methods.AddRange(
                AllMethods(
                    model,
                    baseType));
        }

        methods.AddRange(
            type.Methods);

        return methods;
    }

    private static string RustType(
        RuneApiValueType type)
    {
        var value =
            type.Name switch
            {
                "u64" => "u64",
                "bool" => "bool",
                "string" => "String",
                _ => type.Name
            };

        return type.Optional
            ? $"Option<{value}>"
            : value;
    }

    private static string RustReferenceType(
        RuneApiValueType type) =>
        RustType(type);

    private static string RustMember(
        string name)
    {
        var value =
            Snake(name);

        return value == "type"
            ? "type_"
            : value;
    }

    private static string TypeScriptHostCallbackName(
        string hostName)
    {
        var parts =
            hostName.Split(
                '.',
                StringSplitOptions.RemoveEmptyEntries);

        if (parts.Length == 0)
            return hostName;

        return
            parts[0] +
            string.Concat(
                parts.Skip(1)
                    .Select(
                        part =>
                            char.ToUpperInvariant(part[0]) +
                            part[1..]));
    }

    private static string HostMethodName(
        string hostName) =>
        Snake(
            hostName.Replace(
                '.',
                '_'));

    private static string Constant(
        string type,
        string method) =>
        Snake(
                type + WithoutAsync(method))
            .ToUpperInvariant();

    private static string WithoutAsync(
        string value) =>
        value.EndsWith(
            "Async",
            StringComparison.Ordinal)
            ? value[..^5]
            : value;

    private static string Camel(
        string value) =>
        value.Length == 0
            ? value
            : char.ToLowerInvariant(
                value[0]) +
              value[1..];

    private static string Snake(
        string value)
    {
        var output =
            new StringBuilder();

        for (var index = 0;
             index < value.Length;
             index++)
        {
            var current =
                value[index];

            if (index > 0 &&
                char.IsUpper(current) &&
                (!char.IsUpper(
                     value[index - 1]) ||
                 (index + 1 < value.Length &&
                  char.IsLower(
                      value[index + 1]))))
            {
                output.Append('_');
            }

            output.Append(
                char.ToLowerInvariant(
                    current));
        }

        return output.ToString();
    }
}
