using System.Text;

namespace Rune.Generator;

public static class RuneApiCSharpEmitter
{
    public static IReadOnlyDictionary<string, string>
        Emit(RuneApiModel model) =>
        new SortedDictionary<string, string>(
            StringComparer.Ordinal)
        {
            ["src/Rune.Api/Generated/RuneApi.g.cs"] =
                EmitCSharp(model)
        };

    private static string EmitCSharp(
        RuneApiModel model)
    {
        var text =
            new StringBuilder(
                "// <auto-generated by Rune.Generator />\n" +
                "#nullable enable\n\n" +
                "using System.Globalization;\n" +
                "using System.Text.Json;\n\n" +
                "namespace Rune.Api;\n\n");

        foreach (var type in model.Types)
        {
            if (type.IsEnum)
            {
                text.AppendLine(
                    $"public enum {type.Name}");
                text.AppendLine("{");

                foreach (var member in type.Members)
                {
                    text.AppendLine(
                        $"    {member.Name} = {member.EnumValue},");
                }

                text.AppendLine("}");
                text.AppendLine();
                continue;
            }

            var allMembers =
                AllMembers(
                    model,
                    type);

            var modifier =
                type.Base is null
                    ? "public record"
                    : "public sealed record";

            text.AppendLine(
                $"{modifier} {type.Name}(");

            for (var index = 0;
                 index < allMembers.Count;
                 index++)
            {
                var member = allMembers[index];
                var suffix =
                    index == allMembers.Count - 1
                        ? type.Base is null
                            ? ");"
                            : ")"
                        : ",";

                text.AppendLine(
                    $"    {CSharpType(member.Type)} {member.Name}{suffix}");
            }

            if (type.Base is not null)
            {
                var baseType =
                    model.Types.Single(
                        value =>
                            value.Name == type.Base);

                var baseMembers =
                    AllMembers(
                        model,
                        baseType);

                text.AppendLine(
                    $"    : {type.Base}(");

                for (var index = 0;
                     index < baseMembers.Count;
                     index++)
                {
                    var suffix =
                        index == baseMembers.Count - 1
                            ? ");"
                            : ",";

                    text.AppendLine(
                        $"        {baseMembers[index].Name}{suffix}");
                }
            }
            text.AppendLine();
        }

        text.AppendLine("public enum RuneApiEventType");
        text.AppendLine("{");

        foreach (var runeEvent in model.Events)
            text.AppendLine($"    {runeEvent.Name},");

        text.AppendLine("}");
        text.AppendLine();

        text.AppendLine("public static class NetCordRuneApi");
        text.AppendLine("{");

        foreach (var type in model.Types.Where(type => !type.IsEnum))
        {
            var allMembers =
                AllMembers(
                    model,
                    type);

            text.AppendLine(
                $"    public static {type.Name} Project(");
            text.AppendLine(
                $"        {type.NetCordName} value) =>");
            text.AppendLine("        new(");

            for (var index = 0;
                 index < allMembers.Count;
                 index++)
            {
                var member = allMembers[index];
                var suffix =
                    index == allMembers.Count - 1
                        ? ");"
                        : ",";

                text.AppendLine(
                    $"            {ProjectionExpression(model, member, $"value.{member.Name}")}{suffix}");
            }

            text.AppendLine();
        }

        text.AppendLine("}");
        text.AppendLine();

        text.AppendLine("public static class RuneApiPayload");
        text.AppendLine("{");

        foreach (var payload in
                 model.Events
                     .Select(value => value.Payload)
                     .Distinct(StringComparer.Ordinal))
        {
            text.AppendLine(
                $"    public static JsonElement Serialize({payload} value) =>");
            text.AppendLine(
                "        JsonSerializer.SerializeToElement(Wire(value));");
            text.AppendLine();
        }

        foreach (var type in model.Types.Where(type => !type.IsEnum))
        {
            text.AppendLine(
                $"    private static object Wire({type.Name} value) =>");
            text.AppendLine("        new");
            text.AppendLine("        {");

            var members =
                AllMembers(
                    model,
                    type);

            for (var index = 0;
                 index < members.Count;
                 index++)
            {
                var member = members[index];
                var suffix =
                    index == members.Count - 1
                        ? string.Empty
                        : ",";

                text.AppendLine(
                    $"            {Camel(member.Name)} = {WireExpression(model, member, $"value.{member.Name}")}{suffix}");
            }

            text.AppendLine("        };");
            text.AppendLine();
        }

        text.AppendLine(
            "    private static string Snowflake(ulong value) =>");
        text.AppendLine(
            "        value.ToString(CultureInfo.InvariantCulture);");
        text.AppendLine("}");

        return text.ToString().TrimEnd() + "\n";
    }

    private static string ProjectionExpression(
        RuneApiModel model,
        RuneApiMember member,
        string value)
    {
        if (!member.Type.IsSelectedType)
            return value;

        var selected =
            model.Types.Single(
                type =>
                    type.Name == member.Type.Name);

        if (selected.IsEnum)
        {
            var cast =
                $"({member.Type.Name})(int){value}";

            return member.Type.Optional
                ? $"{value} is null ? null : {cast}"
                : cast;
        }

        return member.Type.Optional
            ? $"{value} is null ? null : Project({value})"
            : $"Project({value})";
    }

    private static string WireExpression(
        RuneApiModel model,
        RuneApiMember member,
        string value)
    {
        if (member.Representation == "snowflake")
        {
            var variable =
                Camel(member.Name) +
                "Snowflake";

            return member.Type.Optional
                ? $"{value} is ulong {variable} ? Snowflake({variable}) : null"
                : $"Snowflake({value})";
        }

        if (!member.Type.IsSelectedType)
            return value;

        var selected =
            model.Types.Single(
                type =>
                    type.Name == member.Type.Name);

        if (selected.IsEnum)
        {
            return member.Type.Optional
                ? $"{value} is {member.Type.Name} enumValue ? (int)enumValue : null"
                : $"(int){value}";
        }

        return member.Type.Optional
            ? $"{value} is null ? null : Wire({value})"
            : $"Wire({value})";
    }

    private static IReadOnlyList<RuneApiMember>
        AllMembers(
            RuneApiModel model,
            RuneApiType type)
    {
        var result =
            new List<RuneApiMember>();

        if (type.Base is not null)
        {
            var baseType =
                model.Types.Single(
                    value =>
                        value.Name == type.Base);

            result.AddRange(
                AllMembers(
                    model,
                    baseType));
        }

        result.AddRange(type.Members);
        return result;
    }

    private static string CSharpType(
        RuneApiValueType type)
    {
        var value =
            type.Name switch
            {
                "u64" => "ulong",
                "bool" => "bool",
                "string" => "string",
                _ => type.Name
            };

        return type.Optional
            ? value + "?"
            : value;
    }

    private static string Camel(
        string value) =>
        value.Length == 0
            ? value
            : char.ToLowerInvariant(value[0]) +
              value[1..];
}
