using System.Text;

namespace Rune.Generator;

public static class RuntimeContractEmitter
{
    public static IReadOnlyDictionary<string, string>
        Emit(
            RuntimeContract contract,
            RuneApiModel api)
    {
        return new SortedDictionary<string, string>(
            StringComparer.Ordinal)
        {
            ["src/Rune.Runtime/Generated/RuntimeProtocol.g.cs"] =
                EmitCSharp(contract),
            ["src/Rune.Firecracker.Runner/src/generated_protocol.rs"] =
                EmitRust(contract, api),
            ["src/Rune.Firecracker.Guest/src/generated_runtime.rs"] =
                EmitGuestRuntime(contract),
            ["src/Rune.Firecracker/generated-runtime.sh"] =
                EmitShellRuntime(contract)
        };
    }

    private static string EmitCSharp(
        RuntimeContract contract)
    {
        var text =
            new StringBuilder(
                "// <auto-generated by Rune.Generator />\n" +
                "#nullable enable\n\n" +
                "using System.Text.Json;\n\n" +
                "using Rune.Api;\n\n" +
                "namespace Rune.Runtime;\n\n");

        text.AppendLine("public static class RuntimeProtocol");
        text.AppendLine("{");
        text.AppendLine(
            $"    public const string InvocationStream = \"{contract.InvocationStream}\";");
        text.AppendLine(
            $"    public const string ResultStream = \"{contract.ResultStream}\";");
        text.AppendLine(
            $"    public const string RunnerConsumerGroup = \"{contract.RunnerConsumerGroup}\";");
        text.AppendLine(
            $"    public const long MaxArtifactBytes = {contract.MaxArtifactBytes};");
        text.AppendLine(
            $"    public const long MaxInvocationBytes = {contract.MaxInvocationBytes};");
        text.AppendLine(
            $"    public const long MaxResultBytes = {contract.MaxResultBytes};");
        text.AppendLine("}");
        text.AppendLine();

        foreach (var type in contract.Types)
        {
            text.AppendLine(
                $"public sealed record {type.Name}(");

            for (var index = 0;
                 index < type.Fields.Count;
                 index++)
            {
                var field = type.Fields[index];
                var suffix =
                    index == type.Fields.Count - 1
                        ? ");"
                        : ",";

                text.AppendLine(
                    $"    {CSharpType(field.Type)} {field.Name}{suffix}");
            }

            text.AppendLine();
        }

        text.AppendLine(
            "public sealed record RuneResultMessage(");
        text.AppendLine("    string StreamId,");
        text.AppendLine("    RuneResultEnvelope Result);");

        return text.ToString().TrimEnd() + "\n";
    }

    private static string EmitRust(
        RuntimeContract contract,
        RuneApiModel api)
    {
        var text =
            new StringBuilder(
                "// <auto-generated by Rune.Generator />\n\n" +
                "use serde::{Deserialize, Serialize};\n" +
                "use serde_json::Value;\n\n");

        text.AppendLine(
            $"pub const INVOCATION_STREAM: &str = \"{contract.InvocationStream}\";");
        text.AppendLine(
            $"pub const RESULT_STREAM: &str = \"{contract.ResultStream}\";");
        text.AppendLine(
            $"pub const RUNNER_CONSUMER_GROUP: &str = \"{contract.RunnerConsumerGroup}\";");
        text.AppendLine(
            $"pub const MAX_ARTIFACT_BYTES: u64 = {contract.MaxArtifactBytes};");
        text.AppendLine(
            $"pub const MAX_INVOCATION_BYTES: usize = {contract.MaxInvocationBytes};");
        text.AppendLine(
            $"pub const MAX_RESULT_BYTES: usize = {contract.MaxResultBytes};");
        text.AppendLine();

        text.AppendLine("#[derive(Debug, Clone, Copy, Serialize, Deserialize)]");
        text.AppendLine("#[allow(clippy::enum_variant_names)]");
        text.AppendLine("#[serde(rename_all = \"camelCase\")]");
        text.AppendLine("pub enum RuneApiEventType {");

        foreach (var runeEvent in api.Events)
            text.AppendLine($"    {runeEvent.Name},");

        text.AppendLine("}");
        text.AppendLine();

        foreach (var type in contract.Types)
        {
            var derives =
                type.Name == "RuneResultEnvelope"
                    ? "#[derive(Debug, Clone, Serialize)]"
                    : "#[derive(Debug, Clone, Serialize, Deserialize)]";

            text.AppendLine(derives);
            text.AppendLine("#[serde(rename_all = \"camelCase\")]");
            text.AppendLine(
                $"pub struct {type.Name} {{");

            foreach (var field in type.Fields)
            {
                text.AppendLine(
                    $"    pub {Snake(field.Name)}: {RustType(field.Type)},");
            }

            text.AppendLine("}");
            text.AppendLine();
        }

        return text.ToString().TrimEnd() + "\n";
    }

    private static string EmitGuestRuntime(
        RuntimeContract contract) =>
        "// <auto-generated by Rune.Generator />\n\n" +
        $"pub const MAX_ARTIFACT_BYTES: usize = {contract.MaxArtifactBytes};\n" +
        $"pub const MAX_INVOCATION_BYTES: usize = {contract.MaxInvocationBytes};\n" +
        $"pub const MAX_RESULT_BYTES: usize = {contract.MaxResultBytes};\n";

    private static string EmitShellRuntime(
        RuntimeContract contract) =>
        "# <auto-generated by Rune.Generator />\n" +
        $"RUNE_MAX_ARTIFACT_BYTES={contract.MaxArtifactBytes}\n" +
        $"RUNE_MAX_INVOCATION_BYTES={contract.MaxInvocationBytes}\n" +
        $"RUNE_MAX_RESULT_BYTES={contract.MaxResultBytes}\n";

    private static string CSharpType(
        string type) =>
        type switch
        {
            "string" => "string",
            "string?" => "string?",
            "u64" => "ulong",
            "guid" => "Guid",
            "datetime" => "DateTimeOffset",
            "json" => "JsonElement",
            "rune-api-event" => "RuneApiEventType",
            "list<RuneHostAction>" => "IReadOnlyList<RuneHostAction>",
            _ => type
        };

    private static string RustType(
        string type) =>
        type switch
        {
            "string" => "String",
            "string?" => "Option<String>",
            "u64" => "u64",
            "guid" => "String",
            "datetime" => "String",
            "json" => "Value",
            "rune-api-event" => "RuneApiEventType",
            "list<RuneHostAction>" => "Vec<RuneHostAction>",
            _ => type
        };

    private static string Snake(
        string value)
    {
        var output = new StringBuilder();

        for (var index = 0;
             index < value.Length;
             index++)
        {
            var current = value[index];

            if (index > 0 &&
                char.IsUpper(current) &&
                (!char.IsUpper(value[index - 1]) ||
                 (index + 1 < value.Length &&
                  char.IsLower(value[index + 1]))))
            {
                output.Append('_');
            }

            output.Append(
                char.ToLowerInvariant(current));
        }

        return output.ToString();
    }
}
